base_images:
  cli-operator-sdk:
    name: cli-operator-sdk
    namespace: ocp
    tag: v1.31.0
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile
  to: aws-load-balancer-operator
operator:
  bundles:
  - as: aws-load-balancer-operator-bundle
    dockerfile_path: bundle.Dockerfile
    skip_building_index: true
  substitutions:
  - pullspec: openshift.io/aws-load-balancer-operator:latest
    with: pipeline:aws-load-balancer-operator
releases:
  initial:
    integration:
      name: "4.17"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.17"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: verify
  commands: make verify
  container:
    from: src
- as: unit
  commands: |
    export XDG_CACHE_HOME=/tmp/.cache
    export ENVTEST_ASSETS_DIR=$(mktemp -d)
    make test
  container:
    from: src
- as: e2e-aws-operator
  steps:
    cluster_profile: aws
    dependencies:
      OO_BUNDLE: aws-load-balancer-operator-bundle
    env:
      OO_INSTALL_MODE: AllNamespaces
      OO_INSTALL_NAMESPACE: aws-load-balancer-operator
    test:
    - as: install
      cli: latest
      commands: |
        oc -n aws-load-balancer-operator rollout status deployment aws-load-balancer-operator-controller-manager
      from: src
      resources:
        requests:
          cpu: 100m
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: aws-load-balancer-install
- as: e2e-aws-rosa-operator
  steps:
    cluster_profile: aws-qe
    dependencies:
      OO_BUNDLE: aws-load-balancer-operator-bundle
    env:
      CHANNEL_GROUP: stable
      EVAL_CONFIG_ENVVARS: "yes"
      OO_CONFIG_ENVVARS: ROLEARN=$(cat ${SHARED_DIR}/operator-role-arn)
      OO_INSTALL_MODE: AllNamespaces
      OO_INSTALL_NAMESPACE: aws-load-balancer-operator
    test:
    - as: install
      cli: latest
      commands: |
        oc -n aws-load-balancer-operator rollout status deployment aws-load-balancer-operator-controller-manager
      from: src
      resources:
        requests:
          cpu: 100m
    - as: test
      cli: latest
      commands: |
        export ALBO_E2E_PLATFORM=ROSA
        export ALBO_E2E_WAFV2_WEBACL_ARN=$(cat ${SHARED_DIR}/wafv2-webacl)
        export ALBO_E2E_WAF_WEBACL_ID=$(cat ${SHARED_DIR}/waf-webacl | head -1)
        export ALBO_E2E_CONTROLLER_ROLE_ARN=$(cat ${SHARED_DIR}/controller-role-arn)
        make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: aws-load-balancer-install-rosa
- as: e2e-aws-proxy-operator
  steps:
    cluster_profile: aws
    dependencies:
      OO_BUNDLE: aws-load-balancer-operator-bundle
    env:
      OO_INSTALL_MODE: AllNamespaces
      OO_INSTALL_NAMESPACE: aws-load-balancer-operator
    test:
    - as: install
      cli: latest
      commands: |
        oc -n aws-load-balancer-operator rollout status deployment aws-load-balancer-operator-controller-manager
      from: src
      resources:
        requests:
          cpu: 100m
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: aws-load-balancer-install-proxy
zz_generated_metadata:
  branch: main
  org: openshift
  repo: aws-load-balancer-operator
