ref:
  as: aws-load-balancer-config-install
  cli: latest
  from: src
  commands: aws-load-balancer-config-install-commands.sh
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
  env:
  - name: OO_INSTALL_NAMESPACE
    documentation: The namespace into which the operator shall be installed.
  - name: CONFIG_DEPLOYMENT
    documentation: The deployment to configure.
    default: "aws-load-balancer-operator-controller-manager"
  - name: CONFIG_CONTAINER
    documentation: The container to configure.
    default: "manager"
  - name: OO_CONFIG_ENVVARS
    documentation: Optional. A comma-separated list of environment variables the operator's deployment will be configured with (key1=value1,key2=value2).
    default: ""
  - name: EVAL_CONFIG_ENVVARS
    documentation: Optional. Execute environment variables by the shell before configuring the deployment.
    default: ""
  documentation: |-
    Configures the deployment installed from a bundle.
